// Code generated by protoc-gen-go-asynq. DO NOT EDIT.
// versions:
// protoc-gen-go-asynq v1.0.13

package example

import (
	context "context"
	json "encoding/json"
	asynq "github.com/hibiken/asynq"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

import (
	"igspkg/igstrace"
	"go.opentelemetry.io/otel/propagation"
	oteltrace "go.opentelemetry.io/otel/trace"
	rkgrpcctx "github.com/rookie-ninja/rk-grpc/v2/middleware/context"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the asynq package it is being compiled against.
var _ = new(context.Context)
var _ = new(asynq.Task)
var _ = new(emptypb.Empty)
var _ = new(proto.Message)
var _ = new(json.InvalidUTF8Error)

type UserJobServer interface {
	CreateUser(context.Context, *CreateUserPayload) error
	UpdateUser(context.Context, *UpdateUserPayload) error
}

func RegisterUserJobServer(mux *asynq.ServeMux, srv UserJobServer) {
	mux.HandleFunc("user:create", _User_CreateUser_Task_Handler(srv))
	mux.HandleFunc("user:update", _User_UpdateUser_Task_Handler(srv))
}

func _User_CreateUser_Task_Handler(srv UserJobServer) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		in := &CreateUserPayload{}

		ctx, span, err := igstrace.Handle_task_before(ctx, task, in)
		if err != nil {
			return err
		}
		err = srv.CreateUser(ctx, in)
		igstrace.Handle_task_after(span, err)

		return err
	}
}

func _User_UpdateUser_Task_Handler(srv UserJobServer) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		in := &UpdateUserPayload{}

		ctx, span, err := igstrace.Handle_task_before(ctx, task, in)
		if err != nil {
			return err
		}
		err = srv.UpdateUser(ctx, in)
		igstrace.Handle_task_after(span, err)

		return err
	}
}

type UserJobClient interface {
	CreateUser(ctx context.Context, req *CreateUserPayload, opts ...asynq.Option) (info *asynq.TaskInfo, err error) //span oteltrace.Span,
	UpdateUser(ctx context.Context, req *UpdateUserPayload, opts ...asynq.Option) (info *asynq.TaskInfo, err error) //span oteltrace.Span,
}

type UserJobClientImpl struct {
	cc *asynq.Client
}

func NewUserJobClient(client *asynq.Client) UserJobClient {
	return &UserJobClientImpl{client}
}

func (c *UserJobClientImpl) CreateUser(ctx context.Context, in *CreateUserPayload, opts ...asynq.Option) (*asynq.TaskInfo, error) { //, oteltrace.Span
	if rkgrpcctx.GetTracerPropagator(ctx) != nil {
		ctx = rkgrpcctx.InjectSpanToNewContext(ctx)
	}

	spanCtx := oteltrace.SpanContextFromContext(ctx)
	ctx, span := igstrace.HolderTracer().Start(oteltrace.ContextWithRemoteSpanContext(ctx, spanCtx), "CreateUserClient")
	defer span.End()

	// get trace metadata
	m := make(map[string]string)
	igstrace.HolderPropagator().Inject(ctx, propagation.MapCarrier(m))

	wrap, err := json.Marshal(igstrace.WrapPayload{
		Trace:   m,
		Payload: in,
	})
	if err != nil {
		return nil, err
	}

	task := asynq.NewTask("user:create", wrap, opts...)

	info, err := c.cc.Enqueue(task)
	if err != nil {
		return nil, err
	}
	return info, nil //, span
}

func (c *UserJobClientImpl) UpdateUser(ctx context.Context, in *UpdateUserPayload, opts ...asynq.Option) (*asynq.TaskInfo, error) { //, oteltrace.Span
	if rkgrpcctx.GetTracerPropagator(ctx) != nil {
		ctx = rkgrpcctx.InjectSpanToNewContext(ctx)
	}

	spanCtx := oteltrace.SpanContextFromContext(ctx)
	ctx, span := igstrace.HolderTracer().Start(oteltrace.ContextWithRemoteSpanContext(ctx, spanCtx), "UpdateUserClient")
	defer span.End()

	// get trace metadata
	m := make(map[string]string)
	igstrace.HolderPropagator().Inject(ctx, propagation.MapCarrier(m))

	wrap, err := json.Marshal(igstrace.WrapPayload{
		Trace:   m,
		Payload: in,
	})
	if err != nil {
		return nil, err
	}

	task := asynq.NewTask("user:update", wrap, opts...)

	info, err := c.cc.Enqueue(task)
	if err != nil {
		return nil, err
	}
	return info, nil //, span
}
